@startuml
title
Рис. 10.13 Взаимодействие объектов модели, представления и контроллера

end title

activate Контроллер
Контроллер -> Представление : рисует представление

activate Представление
deactivate Контроллер
Представление -> Модель : читает содержимое
activate Модель
deactivate Представление
deactivate Модель

activate Контроллер
Контроллер -> Модель : обновляет содержимое
activate Модель
Модель -> Представление : изменилось содержимое
activate Представление
deactivate Модель
deactivate Контроллер
deactivate Представление

Контроллер -> Представление : обновляет представление
activate Контроллер
activate Представление
@enduml